# Generated by Django 4.2.3 on 2023-08-02 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateTimeField(verbose_name='Дата последней попытки')),
                ('status', models.CharField(max_length=100, verbose_name='Статус попытки')),
                ('server_response', models.TextField(blank=True, max_length=100, null=True, verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_theme', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('email_body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время рассылки')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'Раз в день'), (2, 'Раз в неделю'), (3, 'Раз в месяц')], default=1, verbose_name='Периодичность')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Создана'), (2, 'Запущена'), (3, 'Завершена')], default=1, verbose_name='Статус рассылки')),
                ('massage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_service.message')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
